# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test

notifications:
  slack:
    secure: GV9IPLNQcbLx4raoZvZFPBJLhWarinxqmqku+/OSLMY2rWUCYkBA2bPlb5vHCXOek+fJPxMfUVW9Bm+J2HVUlwzQxLPwqZ6Nd71KVmue9ot/6GUrAIi813JdQIlc5R19OSJAtvH7OqorHwQeptAz2s4KmlBIJTHmeiR04mBuhlE=
