language: python
sudo: false
cache:
  - pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
env:
  global:
    - secure: OS5k0TUmxCV0FsKo/9T/UGDCd1Vtirm7/3BXvWbcsr+8TUZ3vpTDoXoAlIrryHLfjaAUyG4nrhzLeGe+VYAdcBr2smm2xHUj46MaKSKIaGKtmXjep8s4dceePKodzLL8dtgyAXEJSSt+FVeTCbmR5lMBXBSVP8xYHb6W1n0Z41g=
  matrix:
    - DJANGO="Django<1.9,>=1.8"
    - DJANGO="Django<1.10,>=1.9"
    - DJANGO="-e git+https://github.com/django/django.git#egg=Django"
matrix:
  allow_failures:
    - python: "pypy3"
    - env: DJANGO="-e git+https://github.com/django/django.git#egg=Django"
install:
  - pip install -U pip
  - pip install -r requirements-dev.txt
  - pip install $DJANGO
  - pip install coveralls
script:
  - isort --check-only --recursive --diff .
  - flake8 --jobs=2 .
  - pep257 --verbose --explain --source --count
  - coverage run --source=closeio -m 'pytest'
after_success:
  coveralls
